[project]
name = 'octo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.impact_report]
path = 'contracts/impact_report.clar'
[contracts.anonymization]
path = 'contracts/anonymization.clar'

clarity_version = 2
epoch = 2.5

[contracts.tokenized_data_transaction]
path = 'contracts/tokenized_data_transaction.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
