[project]
name = 'octo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.candidate_removal]
path = 'contracts/candidate_removal.clar'
clarity_version = 2
epoch = 2.5

[contracts.disk_with_reset_delay]
path = 'contracts/disk_with_reset_delay.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact_report]
path = 'contracts/impact_report.clar'
clarity_version = 1
epoch = 2.05

[contracts.recovery_mechanism]
path = 'contracts/recovery_mechanism.clar'
clarity_version = 2
epoch = 2.5

[contracts.removal_of_candidate]
path = 'contracts/removal_of_candidate.clar'
clarity_version = 2
epoch = 2.5

[contracts.tokenized_data_transaction]
path = 'contracts/tokenized_data_transaction.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
